trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/API/Client/Service/*'
      - 'backend/Common/Services/*'
      - 'backend/Common/Database/*'
      - 'backend/Integrations/GoogleMapsClient/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/API/Client/Service/Function'
  packageName: 'ClientService'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml