trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/API/Business/Employee/*'
      - 'backend/Common/Services/*'
      - 'backend/Common/Database/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/API/Business/Employee/Function'
  packageName: 'Employee'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml