trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/API/Business/Appointment/*'
      - 'backend/Common/Services/*'
      - 'backend/Common/Database/*'
      - 'backend/Common/Core/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/API/Business/Appointment/Function'
  packageName: 'Appointment'

steps:
  - template: ../../../../../DevOps/ci-dotNet8-AzureFunction-template.yml