// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Footer } from "@/components/common/footer";
// import { Header } from "@/components/common/header";
// import { Aside } from "@/components/common/aside";
// import AppNavBar from "@/components/common/app-nav-bar";
// import StoreProvider from "@/components/store-provider"; // Import the StoreProvider
// import RootLayout from "@/app/new-layout";
// import React from "react"; // Importing the new RootLayout
//
// const inter = Inter({ subsets: ["latin"] });
//
// export const metadata: Metadata = {
//     title: "Create Next App",
//     description: "Generated by create next app",
// };
//
// export default function Layout({
//                                    children,
//                                }: Readonly<{
//     children: React.ReactNode;
// }>) {
//     return (
//         <StoreProvider> {/* Wrap the entire layout with the Redux provider */}
//             <RootLayout>
//                 <div className="flex min-h-screen w-full flex-col bg-muted/40">
//                     {/*<Aside/>*/}
//                     <AppNavBar />
//                     <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14">
//                         <Header />
//                         <main className="flex-1 flex flex-col">{children}</main>
//                         {/*<Footer/>*/}
//                     </div>
//                 </div>
//             </RootLayout>
//         </StoreProvider>
//     );
// }


import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import StoreProvider from "@/components/store-provider";
import React from "react"; // Import the StoreProvider

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" className="h-full">
        <body className={`${inter.className} h-full`}>
        <div className="flex min-h-screen h-full w-full flex-col">
            {/* <Aside/> */}
            {/* <AppNavBar/> */}
            {/* <div className="flex flex-col sm:gap-4 sm:py-4 sm:pl-14"> */}
            {/*   <Header/> */}
            {/*   <main className="flex-1 flex flex-col"> */}
            {/*     {children} */}
            {/*   </main> */}
            {/*   <Footer/> */}
            {/* </div> */}

            {/* THE NEWEST */}
            <StoreProvider>
                {children}
            </StoreProvider>
        </div>
        </body>
        </html>
    );
}

