trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'backend/Functions/Background/*'
      - 'backend/Common/Services/*'
      - 'backend/Common/Database/*'
      - 'backend/Common/Core/*'

variables:
  vmImageName: 'windows-latest'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Functions/Background/Function'
  packageName: 'Background'

steps:
  - template: ../../../../DevOps/ci-dotNet8-AzureFunction-template.yml